import type { ScienceField } from "../sciences-types";

const field = {
    slug: "ecology",
    name: "Ecology",
    tagline: "Organisms, environments, and systems they form.",
    overview: "Ecology studies energy, nutrients, populations, communities, conservation, climate links, and applied management of living systems.",
    searchQuery: "ecology biodiversity review",
    subfields: ["Ecosystems", "Populations", "Communities", "Conservation", "Climate", "Applied"],
    concepts: [
      { id: "eco-food", module: "Ecosystem Science", title: "Food chains", whyItMatters: "Simplified paths of who eats whom.", minutes: 11, keyIdeas: ["Core idea: Simplified paths of who eats whom.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Food chains is a standard topic in this field. Simplified paths of who eats whom. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-energy", module: "Ecosystem Science", title: "Energy flow", whyItMatters: "One-way transfer with losses between trophic levels.", minutes: 11, keyIdeas: ["Core idea: One-way transfer with losses between trophic levels.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Energy flow is a standard topic in this field. One-way transfer with losses between trophic levels. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-nut", module: "Ecosystem Science", title: "Nutrient cycles", whyItMatters: "Recycling of elements through biotic and abiotic pools.", minutes: 11, keyIdeas: ["Core idea: Recycling of elements through biotic and abiotic pools.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Nutrient cycles is a standard topic in this field. Recycling of elements through biotic and abiotic pools. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-growth", module: "Population Ecology", title: "Population growth", whyItMatters: "Birth, death, and limits shape abundance.", minutes: 11, keyIdeas: ["Core idea: Birth, death, and limits shape abundance.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Population growth is a standard topic in this field. Birth, death, and limits shape abundance. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-int", module: "Population Ecology", title: "Species interactions", whyItMatters: "Predation, competition, mutualism, and more.", minutes: 11, keyIdeas: ["Core idea: Predation, competition, mutualism, and more.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Species interactions is a standard topic in this field. Predation, competition, mutualism, and more. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-comp", module: "Population Ecology", title: "Competition", whyItMatters: "Shared limiting resources reduce fitness.", minutes: 11, keyIdeas: ["Core idea: Shared limiting resources reduce fitness.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Competition is a standard topic in this field. Shared limiting resources reduce fitness. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-biodiv", module: "Community Ecology", title: "Biodiversity", whyItMatters: "Variety at gene, species, and ecosystem levels.", minutes: 11, keyIdeas: ["Core idea: Variety at gene, species, and ecosystem levels.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Biodiversity is a standard topic in this field. Variety at gene, species, and ecosystem levels. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-rel", module: "Community Ecology", title: "Ecological relationships", whyItMatters: "Networks of interaction in communities.", minutes: 11, keyIdeas: ["Core idea: Networks of interaction in communities.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Ecological relationships is a standard topic in this field. Networks of interaction in communities. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-wild", module: "Conservation Biology", title: "Wildlife protection", whyItMatters: "Preventing extinction of species in the wild.", minutes: 11, keyIdeas: ["Core idea: Preventing extinction of species in the wild.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Wildlife protection is a standard topic in this field. Preventing extinction of species in the wild. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-hab", module: "Conservation Biology", title: "Habitat restoration", whyItMatters: "Assisting recovery of degraded ecosystems.", minutes: 11, keyIdeas: ["Core idea: Assisting recovery of degraded ecosystems.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Habitat restoration is a standard topic in this field. Assisting recovery of degraded ecosystems. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-ext", module: "Conservation Biology", title: "Extinction", whyItMatters: "Permanent loss of species; rates are elevated today.", minutes: 11, keyIdeas: ["Core idea: Permanent loss of species; rates are elevated today.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Extinction is a standard topic in this field. Permanent loss of species; rates are elevated today. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-imp", module: "Climate Ecology", title: "Climate impacts", whyItMatters: "Range shifts, phenology, and ecosystem change.", minutes: 11, keyIdeas: ["Core idea: Range shifts, phenology, and ecosystem change.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Climate impacts is a standard topic in this field. Range shifts, phenology, and ecosystem change. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-carbon", module: "Climate Ecology", title: "Carbon cycles", whyItMatters: "Biological and geological carbon fluxes.", minutes: 11, keyIdeas: ["Core idea: Biological and geological carbon fluxes.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Carbon cycles is a standard topic in this field. Biological and geological carbon fluxes. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-env", module: "Climate Ecology", title: "Environmental change", whyItMatters: "Multiple stressors including climate and land use.", minutes: 11, keyIdeas: ["Core idea: Multiple stressors including climate and land use.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Environmental change is a standard topic in this field. Multiple stressors including climate and land use. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-ag", module: "Applied Ecology", title: "Agriculture", whyItMatters: "Managed ecosystems for food and fiber.", minutes: 11, keyIdeas: ["Core idea: Managed ecosystems for food and fiber.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Agriculture is a standard topic in this field. Managed ecosystems for food and fiber. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-plan", module: "Applied Ecology", title: "Conservation planning", whyItMatters: "Prioritizing actions under limited resources.", minutes: 11, keyIdeas: ["Core idea: Prioritizing actions under limited resources.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Conservation planning is a standard topic in this field. Prioritizing actions under limited resources. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
      { id: "eco-sd", module: "Applied Ecology", title: "Sustainable development", whyItMatters: "Linking human development to ecological limits.", minutes: 11, keyIdeas: ["Core idea: Linking human development to ecological limits.", "Evidence comes from observation, experiment, and theory constrained by data.", "This topic connects to neighboring lessons in the same module."], summary: "Sustainable development is a standard topic in this field. Linking human development to ecological limits. Students master definitions, the main mechanisms or structures involved, and typical evidence used to support claims. Applications and open questions appear in research literature and in later modules. Work through the key ideas, then use the tutor or linked videos to probe details at your level." },
    ],
    landmarks: [
      { title: "Niche concepts", authors: "G. E. Hutchinson", year: 1957, significance: "Ecological niche formalization." }
    ],
  } as ScienceField;
export default field;
